server:
  port: 8888
  servlet:
    context-path: /shiro


spring:
  application:
    name: shiro
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root


mybatis:
  type-aliases-package: com.zaizhi.springboot_jsp_shiro.bean
  mapper-locations: classpath:com/baizhi/mapper/*.xml
